name: Build CloudStream Plugin

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Output Directory & Zip
        run: |
          mkdir -p build_output
          zip -r build_output/UncenxProvider.zip . -x "*.git*"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: UncenxProvider-Plugin
          path: build_output/
